config/routes.rb
CCBClub::Application.routes.draw do

  resources :newsletters, only: [:index, :new, :create, :destroy]
  
  devise_for :users
  resources :events

  root :to => 'ccb_core#index'

  match 'about', :to => 'ccb_core#about', via:[:get]

  match '/join', :to => 'ccb_core#join', via:[:get]

  match '/need', :to => 'ccb_core#need', via:[:get]
  
  match '/newsletters', :to => 'newsletters#newsletters', via:[:get]

  match '/club', :to => 'ccb_core#club', via:[:get]

  match '/location', :to => 'ccb_core#location', via:[:get]

  match '/book', :to => 'ccb_core#book', via:[:get]

  match '/links', :to => 'ccb_core#links', via:[:get]

end

app/models/event.rb
class Event < ActiveRecord::Base
  scope :current_and_future, lambda { where('date >= ?', Date.today) }
  validates_presence_of :title,:date, :description 
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ccb_core_controller.rb
class CcbCoreController < ApplicationController
 def index
    @title = "Home Page"
  end

  def about
    @title = "About the Club"
  end

  def join
    @title = "How to Join"
  end

  def need
    @title = "What you need"
  end


  def club
    @title = "Club Matters"
  end

  def location
    @title = "How to get there"
  end

  def book
    @title = "Book a Lawn"
  end

  def links
    @title = "Links to Croquet Sites"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
 
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]
  
  

  # GET /events
  # GET /events.json
  #Shows current and future events only
  def index
    @events =  Event.current_and_future
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :date, :description)
    end
  
  private
    def require_authentication
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]
  
  
  
 def index
   @newsletters = Newsletter.all
 end

 def new
    @newsletters = Newsletter.new
 end
  
 def create
    @newsletters = Newsletter.new(newsletters_params)

    if @newsletters.save
      redirect_to newsletters_path, notice: "The newsletters #{@newsletters.name} has been uploaded."
    else
      render "new"
    end
 end
  
 def destroy
    @newsletters= Newsletter.find(params[:id])
    @newsletters.destroy
    redirect_to newsletters_path, notice:  "The newsletters #{@newsletters.name} has been deleted."
 end
  
  

private
 def newsletters_params
    params.require(:newsletter).permit(:name, :attachment)
 end
  
 def require_authentication
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = "Cheam Croquet & Bowls Club"
		if @title.nil?
			base_title
		else
			"#{base_title}|#{@title}"
		end
	end
end

app/helpers/ccb_core_helper.rb
module CcbCoreHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/ccb_core/about.html.erb
<h1>About the Club</h1>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse ut pharetra quam. Sed ac ante non urna luctus iaculis id ac risus. 
  Integer consequat vehicula tortor sed ultricies. Nullam nec hendrerit urna. Pellentesque nulla lacus, rutrum vel libero nec, volutpat 
  viverra ligula. Nunc feugiat vitae magna dignissim rhoncus. Sed in nibh fermentum urna interdum sollicitudin vitae quis urna. Phasellus 
  metus turpis, venenatis lacinia viverra quis, rhoncus vel libero. Duis non ipsum at justo iaculis ultrices. Morbi sagittis turpis sit amet
  vulputate fringilla. Fusce sed ante non lorem imperdiet adipiscing sed vitae neque. Suspendisse auctor et justo nec sodales. Aliquam erat 
  volutpat. Proin pellentesque congue tempus. Quisque eget porta neque.

  Donec molestie libero libero, at viverra urna luctus eget. Duis fringilla pellentesque tempor. Nullam eget elit vitae tellus lacinia 
  sollicitudin. Donec euismod consequat quam at eleifend. Vestibulum non magna urna. Nunc mi tortor, malesuada vel auctor sit amet, vestibulum 
  tristique ante. Sed molestie lobortis sagittis. Phasellus risus nisl, lobortis ac odio ut, eleifend interdum felis.

  Aliquam metus mi, consequat nec tortor sodales, adipiscing pellentesque urna. Sed rhoncus interdum orci non condimentum. Donec ullamcorper, 
  urna eget porttitor cursus, libero felis cursus lacus, at mollis felis sapien vitae nisl. Maecenas consequat, neque id ultrices vehicula, 
  arcu nunc dictum lacus, vel venenatis dui ligula eu eros. Donec vel risus viverra, malesuada neque sed, dignissim sem. Phasellus sed 
  scelerisque mi. Nunc ipsum urna, fermentum a tempus eu, varius non mi. In hendrerit nisi turpis, eget consectetur massa auctor sit amet. 
  Cras eget volutpat magna, sed pretium eros. Vestibulum aliquet egestas euismod. Nullam vel risus eu dui suscipit sagittis at ut lorem. 
  Nulla felis mi, sodales vel vestibulum lobortis, dictum nec dui. In dolor nisi, pellentesque id neque vel, commodo pharetra purus.

  Nam molestie eu ante vitae sodales. Cras consectetur tempus sagittis. Vestibulum ultricies nibh lectus, vitae fringilla arcu vehicula ac. 
  Pellentesque est lectus, hendrerit ut ante id, suscipit convallis massa. Nulla facilisi. Etiam pulvinar magna in quam iaculis aliquam. 
  Suspendisse quis erat erat. Proin rutrum fringilla sem, et lacinia turpis tempor ut. Phasellus tortor lectus, tincidunt dignissim pulvinar non, 
  tincidunt nec velit. Curabitur auctor nec dolor a ullamcorper. Pellentesque gravida a mi et fringilla. Phasellus eu dignissim libero.
</p>

app/views/ccb_core/book.html.erb
<h1>Book a Lawn</h1>

app/views/ccb_core/club.html.erb
<h1>Club Matters</h1>
<p>
  Aliquam placerat quam porttitor massa fermentum, quis pulvinar felis posuere. Proin urna nunc, mattis at nibh vel, egestas 
  aliquam massa. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vel odio eget massa iaculis vehicula 
  et quis odio. Suspendisse non sapien vestibulum, suscipit urna a, euismod neque. Sed malesuada purus sodales scelerisque 
  hendrerit. Vestibulum nunc purus, congue convallis dapibus at, posuere at tortor. Sed elementum elit id ultricies varius. 
  Nunc venenatis elit ut mauris pellentesque, hendrerit tincidunt purus pulvinar. Cum sociis natoque penatibus et magnis dis 
  parturient montes, nascetur ridiculus mus. Integer sodales felis id commodo luctus. Etiam a dictum dolor. Praesent nunc 
  mauris, commodo eget semper non, porttitor sed ante. Donec commodo nulla ac sem rhoncus, vel euismod turpis lacinia.

  Nulla vel elementum lacus. Nulla molestie, nibh vel aliquam placerat, lorem ipsum dapibus orci, quis congue turpis massa a 
  velit. Morbi facilisis sollicitudin tellus quis tincidunt. Sed auctor nibh a vestibulum mollis. Suspendisse potenti. Sed 
  interdum a augue quis viverra. Sed arcu odio, iaculis venenatis nibh nec, consectetur vehicula erat. Proin ut interdum leo,
  quis pulvinar elit. Suspendisse potenti. Nulla lobortis mauris id elit euismod venenatis. Nunc malesuada laoreet sollicitudin. 
  Praesent rhoncus, sapien ut sodales eleifend, ipsum felis lacinia tortor, sit amet vulputate mi turpis sit amet lacus. S
  uspendisse et velit nec elit malesuada aliquam. Pellentesque pulvinar velit vitae auctor mollis. Integer viverra pulvinar magna, 
  sed venenatis magna rutrum a. Integer diam purus, dapibus eget magna ac, aliquam hendrerit purus.
</p>

app/views/ccb_core/index.html.erb
<p> 
  There are Club sessions for Golf Croquet on Tuesday and Wednesday mornings, Thursday and Sunday afternoons and Wednesday 
  evening. There is one session for Association Croquet each Sunday morning and two sessions for Bowls on Monday and Wednesday 
  afternoons.
  Some members have very kindly agreed to try to attend some of the Golf Croquet Club sessions on a regular basis so that any member 
  turning up has someone to play with. These are normally the Tuesday and Wednesday morning and Thursday afternoon sessions.
  If you arrive at a Club session and there is no one else there it is a good opportunity to set the hoops out and do some practice.
  This sort of practice can be very valuable in improving your skills. 
  Please play on the full lawn when you can as it is much better practice. The half lawns should normally only be used when there are 
  more than 8 members at a session.
</p>

app/views/ccb_core/join.html.erb
<h1>How to Join</h1>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec et leo placerat, dictum tortor a, varius libero. 
  Nam quis felis a tortor sollicitudin tristique. Phasellus consectetur sed leo vel dignissim. Donec tincidunt accumsan 
  quam, id vulputate mi luctus ac. Sed venenatis scelerisque augue sit amet aliquet. Nam auctor adipiscing dictum. 
  Duis sed tortor ac tellus ultricies rhoncus at sit amet eros. In adipiscing et diam a lobortis.
</p>

app/views/ccb_core/links.html.erb
<h1>Links to Croquet Sites</h1></br>
<%= link_to "SECF", "http://www.southeastcroquet.org.uk/" %></br>   
<%= link_to "The Croquet Association", "http://www.croquet.org.uk/"%></br>  
<%= link_to "Croquet Academy", "http://www.thecroquetacademy.com/"%></br> 
<%= link_to "Croquet Equipment", need_path %></br>
<%= link_to "Croquet Glossary", "http://cornwall-croquet.org.uk/croquet_glossary.htm"%> 

app/views/ccb_core/location.html.erb
<h1>How to get there</h1>
<p>
  Mauris egestas, dui ac rhoncus hendrerit, ligula dolor vulputate velit, ut sollicitudin odio augue sit amet nunc.
  Donec ac cursus elit, id porttitor tortor. In sodales at nisl mollis feugiat. Aliquam erat volutpat. Nunc egestas 
  nunc sed fermentum auctor. Pellentesque quis velit non sapien vulputate posuere. Nunc a diam lorem. Aenean vestibulum 
  ut tortor eget porta. Quisque porttitor, lorem a convallis condimentum, ligula lacus pretium arcu, id facilisis est massa 
  ut tortor. Nunc molestie et purus nec molestie. Nulla ultrices bibendum congue. Praesent interdum id nisl a convallis.
</p>

app/views/ccb_core/need.html.erb
<h1>What you need</h1>
<p>
  When you join the Club and start to learn how to play the game you do not need to be involved in any expense as far as equipment is concerned.
  Initially you can borrow a club mallet and use it until you are sure that you like the game and until you know what sort of mallet you want to buy for 
  your personal use. The only requirement to start with is that you should wear flat-soled shoes on the lawn to avoid damage.
  When you start playing in matches it is suggested that you get "whites" to play in as this is the accepted norm for matches and tournament play
  Get more information via the <%= link_to "Home Page", root_path %>
</p>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1><%= Time.now.year %> Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
</br>
</br>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><b><%= event.title %></b></td>
        <td><%= event.date %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_header.html.erb
<header>
<img src="/images/cheam.jpg" alt="cheam logo" width="110" height="110" /></img>
<h2><div align="center"><%= link_to "Cheam Croquet & Bowls Club", root_path %></div></h2>
</header>

app/views/layouts/_navigation.html.erb
<nav>
	<ul>
		<li><%= link_to "Home Page", root_path %></li>
		<li><%= link_to "About the Club", about_path %></li>  
		<li><%= link_to "How to Join", join_path %></li>
		<li><%= link_to "What you need", need_path %></li>
    	<li><%= link_to "2013 Programme", events_path %></li>
		<li><%= link_to "Newsletters", newsletters_path %></li>
		<li><%= link_to "Club Matters", club_path %></li>
		<li><%= link_to "How to get there", location_path %></li>
		<li><%= link_to "Book a Lawn", book_path %></li>
		<li><%= link_to "Links to Croquet Sites", links_path %></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  
<body>
  <section class="sidebar" id="right">
    <% if user_signed_in? %>
      Signed in as <%= current_user.email %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to "Sign_up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
    <% end %>
  </section>

  <%= render 'layouts/header' %></br></br>
  <%= render 'layouts/navigation' %>
    
  <div align="center">
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
</body>

</html>

app/views/newsletters/create.html.erb
<h1>Newsletters#create</h1>
<p>Find me in app/views/newsletters/create.html.erb</p>

app/views/newsletters/destroy.html.erb
<h1>Newsletters#destroy</h1>
<p>Find me in app/views/newsletters/destroy.html.erb</p>

app/views/newsletters/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>

<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
  </tr>
  </thead>
  <tbody>
    <% @newsletters.each do |newsletters| %>
      <tr>
                <td><%= link_to newsletters.name, newsletters.attachment_url %></td>
        <td><%= button_to "Delete",  newsletters, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{newsletters.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h3><%= link_to "Upload Newsletter", new_newsletter_path, class: "btn btn-primary" %></h3>

app/views/newsletters/new.html.erb
<% if !@newsletters.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @newsletters.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @newsletters, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>